// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW1xnaGV5XWwObyGz3SgUwdc7_Yy8OqxE',
    appId: '1:699971443199:web:9bb214e2a102912210efca',
    messagingSenderId: '699971443199',
    projectId: 'one-menu-a58ad',
    authDomain: 'one-menu-a58ad.firebaseapp.com',
    storageBucket: 'one-menu-a58ad.appspot.com',
    measurementId: 'G-1DCG7998ZL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIo7bXDud7Aasy6lXn_kmCZZTct6agYNE',
    appId: '1:699971443199:android:890495686452b77e10efca',
    messagingSenderId: '699971443199',
    projectId: 'one-menu-a58ad',
    storageBucket: 'one-menu-a58ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHBxwIgpvSM2WaYfbP2sTbw9AsPqg6P30',
    appId: '1:699971443199:ios:0ff81719295929a610efca',
    messagingSenderId: '699971443199',
    projectId: 'one-menu-a58ad',
    storageBucket: 'one-menu-a58ad.appspot.com',
    androidClientId: '699971443199-8e4p4hoa09vlk060d8o1358kfo82c6ie.apps.googleusercontent.com',
    iosClientId: '699971443199-38ovo0op2n76m5nafkmdav656jie67g6.apps.googleusercontent.com',
    iosBundleId: 'com.onemenu.ios',
  );
}
